In [8]:
import numpy as np

# Створимо матрицю A
A = np.array([[1,2],
              [4, -1]])

# Створимо матрицю B
B = np.array([[2,-3],
              [4, 1]])

# Обчислимо матрицю C
C = np.dot(A, B) - np.dot(B, A)

print("Матриця C:")
print(C)

Матриця C:
[[ 20  -8]
 [ -4 -20]]


In [9]:
import numpy as np

# Створимо матрицю A
A = np.array([[-1,2],
              [0, 1]])

# Обчислимо матрицю C
C = pow(A,2)


print(C)

[[1 4]
 [0 1]]


In [10]:
import numpy as np

# Створимо матрицю A
A = np.array([[3,5],
              [6, -1]])

# Створимо матрицю B
B = np.array([[2,1],
              [-3, 2]])

# Обчислимо матрицю C
C = A * B

print("Матриця C:")
print(C)

Матриця C:
[[  6   5]
 [-18  -2]]


In [11]:
import numpy as np

# Для матриці 4x4
B = np.array([[1, 2, 3,4],
              [3, -1, 2,5],
              [1, 2, 3,4],
              [1,3,4,5]
              ])

det_4x4 = np.linalg.det(B)


print("Визначник матриці 4x4:", det_4x4)

Визначник матриці 4x4: 0.0


In [12]:
import numpy as np

A = np.array([[1, -2, 1],
              [2, -1, 1],
              [3, 2, 2]])

B = np.array([4, 3, 2])
detA = np.linalg.det(A)

A_x = A.copy()
A_x[:, 0] = B
detA_x = np.linalg.det(A_x)

A_y = A.copy()
A_y[:, 1] = B
detA_y = np.linalg.det(A_y)

A_z = A.copy()
A_z[:, 2] = B
detA_z = np.linalg.det(A_z)

x = detA_x / detA
y = detA_y / detA
z = detA_z / detA

print("Решение:")
print("x =", x)
print("y =", y)
print("z =", z)

Решение:
x = 0.0
y = -1.0
z = 2.0


In [13]:
import numpy as np

# Для матриці 3x3
B = np.array([[2, 3, 4],
              [1, 0, 6],
              [7, 8, 9]])

det_3x3 = np.linalg.det(B)


print("Визначник матриці 3x3:", det_3x3)

Визначник матриці 3x3: 35.00000000000001


In [14]:
import numpy as np
N = 5
M = 6 

A = np.random.randint(1, 11, size=(N, M))

total_sum = np.sum(A)

column_sums = np.sum(A, axis=0)

column_fractions = column_sums / total_sum

print("Матриця A:")
print(A)

print("\nСума всіх елементів матриці:", total_sum)

print("\nСуми елементів кожного стовпця:")
for i, col_sum in enumerate(column_sums):
    print(f"Сума стовпця {i + 1}: {col_sum}")

print("\nДолі сум елементів кожного стовпця відносно загальної суми:")
for i, fraction in enumerate(column_fractions):
    print(f"Доля стовпця {i + 1}: {fraction:.2%}")

Матриця A:
[[ 1  3 10  7  2 10]
 [ 7  3  9  2  5  1]
 [10  1  2  3  3  9]
 [10 10  1  5  9  7]
 [ 2  5  7  2  1 10]]

Сума всіх елементів матриці: 157

Суми елементів кожного стовпця:
Сума стовпця 1: 30
Сума стовпця 2: 22
Сума стовпця 3: 29
Сума стовпця 4: 19
Сума стовпця 5: 20
Сума стовпця 6: 37

Долі сум елементів кожного стовпця відносно загальної суми:
Доля стовпця 1: 19.11%
Доля стовпця 2: 14.01%
Доля стовпця 3: 18.47%
Доля стовпця 4: 12.10%
Доля стовпця 5: 12.74%
Доля стовпця 6: 23.57%


## Next steps 🏃

This is just a short introduction to JupyterLab and Jupyter Notebooks. See below for some more ways to interact with tools in the Jupyter ecosystem, and its community.

### Other notebooks in this demo

Here are some other notebooks in this demo. Each of the items below corresponds to a file or folder in the **file browser to the left**.

- [**`Lorenz.ipynb`**](Lorenz.ipynb) uses Python to demonstrate interactive visualizations and computations around the [Lorenz system](https://en.wikipedia.org/wiki/Lorenz_system). It shows off basic Python functionality, including more visualizations, data structures, and scientific computing libraries.
- [**`sqlite.ipynb`**](sqlite.ipynb) demonstrates how an in-browser sqlite kernel to run your own SQL commands from the notebook. It uses the [jupyterlite/xeus-sqlite-kernel](https://github.com/jupyterlite/xeus-sqlite-kernel).

### Other sources of information in Jupyter

- **More on using JupyterLab**: See [the JupyterLab documentation](https://jupyterlab.readthedocs.io/en/stable/) for more thorough information about how to install and use JupyterLab.
- **More interactive demos**: See [try.jupyter.org](https://try.jupyter.org) for more interactive demos with the Jupyter ecosystem.
- **Learn more about Jupyter**: See [the Jupyter community documentation](https://docs.jupyter.org) to learn more about the project, its community and tools, and how to get involved.
- **Join our discussions**: The [Jupyter Community Forum](https://discourse.jupyter.org) is a place where many in the Jupyter community ask questions, help one another, and discuss issues around interactive computing and our ecosystem.